#!/usr/bin/env python3
"""Generate docs/contact/team.md from docs/contact/_team.yml.

Reads the YAML data file that defines team members, filter chips,
and intro text, then writes a fully-rendered team.md with all the
HTML divs, filter buttons, badges, and image references.

Requires PyYAML. If missing:
    pip install pyyaml  --break-system-packages

Usage:
    python scripts/build_team_page.py                # writes team.md
    python scripts/build_team_page.py --check        # dry run, prints diff summary

Called automatically by .github/workflows/build-team.yml on push to _team.yml.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML is required. Install with: pip install pyyaml --break-system-packages",
          file=sys.stderr)
    sys.exit(1)


REPO_ROOT = Path(__file__).resolve().parent.parent
YAML_PATH = REPO_ROOT / "docs" / "contact" / "_team.yml"
OUTPUT_PATH = REPO_ROOT / "docs" / "contact" / "team.md"
IMG_PREFIX = "../assets/images/transmodel-cen/"

FRONTMATTER = """---
hide:
  - toc
  - navigation
---
"""

GENERATED_BANNER = """<!--
  This file is generated from _team.yml by scripts/build_team_page.py.
  Do not edit this file directly — edit _team.yml and re-run the script
  (or push, and the GitHub Action regenerates it automatically).
-->
"""


def render_standards_box(standards: list[dict]) -> str:
    """Render the top box of standards contacts (Material grid.cards)."""
    if not standards:
        return ""
    lines = [
        "## Standards contacts",
        "",
        "Full contact information for each Subgroup — including GitHub, artefacts, and FAQ — will land here as the standards' own sections are filled in.",
        "",
        '<div class="grid cards" markdown>',
        "",
    ]
    for std in standards:
        icon = std.get("icon", "material-help-circle")
        icon_ref = f":{icon.replace('-', '_', 1)}:" if icon.startswith("material-") else f":{icon}:"
        # Correct Material icon reference format is :material-name-with-hyphens:
        icon_ref = f":{std['icon']}:"
        label = std["label"]
        subgroup = std.get("subgroup", "")
        link = std["link"]
        heading = f"{label} ({subgroup})" if subgroup else label
        lines += [
            f"-   {icon_ref} **{heading}**",
            "",
            "    ---",
            "",
            "    Contact, GitHub links, FAQ and artefacts.",
            "",
            f"    [Go to {label} →]({link})",
            "",
        ]
    lines.append("</div>")
    return "\n".join(lines)


def sort_members(members: list[dict]) -> list[dict]:
    """Sort: leaders first (alphabetical), then honorary (alphabetical), then rest (alphabetical)."""
    def key(m):
        if m.get("leader"):
            group = 0
        elif m.get("honorary"):
            group = 1
        else:
            group = 2
        return (group, m["name"].lower())
    return sorted(members, key=key)


def render_filter(filters: list[dict]) -> str:
    lines = [
        '<div class="team-filter" markdown>',
        '<span class="team-filter-label">Filter by standard:</span>',
    ]
    for f in filters:
        lines.append(f'<button data-filter="{f["id"]}">{f["label"]}</button>')
    lines.append("</div>")
    return "\n".join(lines)


def render_member(member: dict) -> str:
    name = member["name"]
    affiliation = member.get("affiliation")
    role = member.get("role")
    photo = member.get("photo")
    photo_missing = member.get("photo_missing", False)
    photo_width = member.get("photo_width", 150)
    standards = member.get("standards") or []
    honorary = member.get("honorary", False)
    leader = member.get("leader", False)

    # CSS classes
    classes = ["team-member"]
    if honorary:
        classes.append("honorary")
    if leader:
        classes.append("leader")

    # Standards data attribute
    std_attr = ",".join(standards)

    # Heading — "Name — Affiliation" or just "Name"
    heading = f"### {name}"
    if affiliation:
        heading = f"### {name} — {affiliation}"

    # Body content
    body_lines = [heading, ""]

    if role:
        body_lines += [role, ""]

    # Standards line
    if standards:
        pretty = {
            "transmodel": "Transmodel",
            "netex": "NeTEx",
            "siri": "SIRI",
            "ojp": "OJP",
            "opra": "OpRa",
            "eudit": "EUDIT",
            "efip": "EFIP",
            "cyclinfra": "CyclInfra",
            "bt4pt": "BT4PT",
        }
        std_names = [pretty.get(s, s) for s in standards]
        body_lines += [f"**Standards:** {' · '.join(std_names)}", ""]
    else:
        body_lines += ["**Standards:** *to be confirmed*", ""]

    # Photo
    if photo_missing or not photo:
        body_lines.append("*(photo missing)*")
    elif photo:
        body_lines.append(
            f'![{name}]({IMG_PREFIX}{photo}){{ width="{photo_width}" }}'
        )

    inner = "\n".join(body_lines)

    return (
        f'<div class="{" ".join(classes)}" data-standards="{std_attr}" markdown>\n'
        f'{inner}\n'
        f'</div>'
    )


def build(data: dict) -> str:
    parts = [FRONTMATTER.strip(), "", GENERATED_BANNER.strip(), "", "# Team", ""]

    if data.get("intro"):
        parts.append(data["intro"].strip())
        parts.append("")

    if data.get("note"):
        parts.append(data["note"].strip())
        parts.append("")

    # Standards contacts box
    if data.get("standards"):
        parts.append(render_standards_box(data["standards"]))
        parts.append("")

    # Filter chips
    parts.append(render_filter(data["filters"]))
    parts.append("")

    # Team members in a responsive grid, sorted leader → honorary → rest
    parts.append('<div class="team-grid" markdown>')
    parts.append("")
    for member in sort_members(data["members"]):
        parts.append(render_member(member))
        parts.append("")
    parts.append("</div>")

    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true",
                        help="Don't write; just verify the YAML parses and print summary.")
    args = parser.parse_args()

    if not YAML_PATH.exists():
        print(f"ERROR: {YAML_PATH} not found", file=sys.stderr)
        return 1

    with open(YAML_PATH, "r", encoding="utf-8") as fh:
        data = yaml.safe_load(fh)

    if not data or "members" not in data:
        print("ERROR: YAML has no 'members' key.", file=sys.stderr)
        return 1

    output = build(data)

    if args.check:
        n = len(data["members"])
        n_honorary = sum(1 for m in data["members"] if m.get("honorary"))
        n_leader = sum(1 for m in data["members"] if m.get("leader"))
        print(f"Parsed {n} members "
              f"({n_honorary} honorary, {n_leader} leader).")
        print(f"Would write {len(output)} bytes to {OUTPUT_PATH.relative_to(REPO_ROOT)}.")
        return 0

    OUTPUT_PATH.write_text(output, encoding="utf-8")
    print(f"Wrote {len(output)} bytes to {OUTPUT_PATH.relative_to(REPO_ROOT)}.")
    print(f"({len(data['members'])} members)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
